"""Export the selected scikit-learn Decision Tree and scaler as a C++ header."""

import argparse
from pathlib import Path

import numpy as np

from data_processing import FEATURE_COLUMNS, ROOT
from model_training import train_selected_model

DEFAULT_OUTPUT = ROOT / "firmware" / "motion_classifier" / "model_data.h"


def cpp_array(name, values, ctype, formatter=str):
    body = ", ".join(formatter(value) for value in values)
    return f"const {ctype} {name}[] = {{\n  {body}\n}};\n"


def export_header(tree, scaler, output):
    structure = tree.tree_
    node_class = np.argmax(structure.value, axis=2).flatten().astype(int)
    is_leaf = structure.children_left == -1

    sections = [
        "#pragma once\n",
        "// Auto-generated by training/export_tree.py. Do not edit manually.\n",
        f"const int FEATURE_COUNT = {len(FEATURE_COLUMNS)};\n",
        f"const int TREE_NODE_COUNT = {structure.node_count};\n\n",
        cpp_array("feature", structure.feature, "int", lambda x: str(int(x))),
        cpp_array("threshold", structure.threshold, "float", lambda x: f"{float(x):.6f}f"),
        cpp_array("left", structure.children_left, "int", lambda x: str(int(x))),
        cpp_array("right", structure.children_right, "int", lambda x: str(int(x))),
        cpp_array("node_class", node_class, "int", lambda x: str(int(x))),
        cpp_array("is_leaf", is_leaf, "bool", lambda x: "true" if x else "false"),
        cpp_array("mean_vals", scaler.mean_, "float", lambda x: f"{float(x):.6f}f"),
        cpp_array("scale_vals", scaler.scale_, "float", lambda x: f"{float(x):.6f}f"),
        "\n// Class mapping from scikit-learn's sorted class labels:\n",
    ]
    for index, label in enumerate(tree.classes_):
        sections.append(f"// {index} -> {label}\n")

    output = Path(output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("".join(sections), encoding="utf-8")
    print(f"Exported {structure.node_count} nodes to {output}")


def main():
    parser = argparse.ArgumentParser(description="Export the trained model to a C++ header.")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    tree, scaler, *_ = train_selected_model(verbose=False)
    export_header(tree, scaler, args.output)


if __name__ == "__main__":
    main()
